### ISSUE TITLE
MacOS: Menu item for changelog leads to page not found

### ISSUE THREAD

**Issue by gingerbeardman** [Orama-Interactive/Pixelorama#275]
The URL in the code is correct:
- https://github.com/Orama-Interactive/Pixelorama/blob/master/CHANGELOG.md#v07---2020-05-16

The one that is opened is:
- https://github.com/Orama-Interactive/Pixelorama/blob/master/CHANGELOG.md%23v07---2020-05-16

As you can see the # is being escaped.

**Comment by Schweini07** [comment]
Is fixed on 0.8-dev.

**Comment by OverloadedOrama** [comment]
It shouldn't have been fixed on 0.8-dev. This is either an OS issue, or a browser issue (or a Godot issue), as I never have this problem. I'm on Windows 10, using Google Chrome. What's your OS and browser?

**Comment by luiq54** [comment]
I tested it on Linux- Firefox on 0.7 and 0.8-dev and couldn't replicate the issue.

**Comment by gingerbeardman** [comment]
I'm on macOS and use Safari, but the problem persists with Chrome, Firefox and Opera.

Also, I checked 0.8-dev and did not see any change/commit related to this issue.

**Comment by OverloadedOrama** [comment]
I'm not sure how this can be fixed. As a workaround, I made it so that if you're on a Mac, the menu item opens the changelog at the start of the file. The only issue with this is that it might confuse users that are using older versions.

It sounds like a macOS or a Godot issue. Maybe it's worth the try to open an issue in Godot's repository, with a minimal reproduction project. I'll close this for now, but if anyone has an idea of how this can be fixed, feel free to comment, or open a PR.

**Comment by OverloadedOrama** [comment]
Oh, looks like someone already addressed the issue there. There is an open PR in Godot https://github.com/godotengine/godot/pull/39973
